# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AllergyInsider' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AllergyInsider
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # or pod ‘Firebase/AnalyticsWithoutAdIdSupport’
  # for Analytics without IDFA collection capability

  # add pods for any other desired Firebase products
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  # https://firebase.google.com/docs/ios/setup#available-pods

  # Add the pod for Firebase Crashlytics
  pod 'Firebase/Crashlytics'

  # Recommended: Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

end
